spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/blog_engine?serverTimezone=Europe/Moscow&useUnicode=true&characterEncoding=utf8
    username: root
    password: testtest
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
#      mode: always
#      data-locations: classpath:/data.sql
  jpa:
    hibernate:
      ddl-auto: create